name: test
on: push
jobs:
  test_my_prj:
    runs-on: ubuntu-latest
    steps:
      -name: Get the repository code
       uses: actions/checkout@v3
      - name: Install dependentis
        run: npm ci
      - name: test app
        run: npm run test